name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94731eed993ff4158be406c592d40d670d5143afb3663d1d70ad430ebe4d4747"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
