name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbdbee762495e3035e31a7736b1e40e4f57702e264e4898b18c272a1c10d94a8"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
