name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f33020f5577e791475e9c248b0f0d3b92b399b76d8883147ee509a9b7b29ca82"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
