name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "372062562e2e6ac2ab28e69e41dcd836aef24e64f525ecfcd3a5159a7859df4f"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
