name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df7372c798c1081d725574b1a2082cc9ace9da88e424938c9db6cbd54fe53589"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
