name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40fbd7b9b27e3b664873a0f790fd998f13d7cea064a68dcd735dbf9395015daa"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
