name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4d3b4816e2e9d0adb39bc9181ca6b0b30d07607d23e99e1d8138f4c8d09b1c7"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
