name = "TSMC-Craft"
author = "MikeAtom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31f8e85cea9bafe691e5079b81e353465835ccbfe04c53c8f2702198ac894581"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
